import type { ThemeData } from "../types/pipeline.js";

export function buildScenePrompt(theme: ThemeData): string {
  return [
    "theme.jsonをもとに、睡眠/ヒーリング用のノーボイス環境動画のscene.jsonをJSONオブジェクトだけで作成してください。",
    "健康効能の断定、不眠や病気が治る表現、医療的な効果の表現は禁止です。",
    "seedはシステムが決定するため、JSONに含めないでください。",
    "",
    "必須スキーマ:",
    "{",
    '  "sceneId": "英小文字・数字・ハイフンの短いID",',
    '  "title": "短い日本語タイトル",',
    '  "storyline": "説明欄に載せられる短い世界観。効能断定は禁止。",',
    '  "durationSeconds": 60,',
    '  "audio": {',
    '    "preset": "rain",',
    '    "layers": [',
    '      { "id": "steady-rain", "type": "rain", "gain": 0.8 },',
    '      { "id": "soft-drops", "type": "drops", "gain": 0.35 }',
    "    ]",
    "  },",
    '  "visual": {',
    '    "preset": "particles",',
    '    "params": { "particleCount": 240, "drift": 0.35, "brightness": 0.55, "loopSeconds": 10 }',
    "  }",
    "}",
    "",
    "制約:",
    "- durationSeconds: 10以上3600以下。P0では原則60。",
    "- audio.preset: rain のみ。",
    "- audio.layers[].type: rain または drops のみ。",
    "- audio.layers[].gain: 0以上1以下。",
    "- visual.preset: particles のみ。",
    "- visual.params.particleCount: 1以上5000以下の整数。",
    "- visual.params.drift: 0以上2以下。",
    "- visual.params.brightness: 0以上1以下。",
    "- visual.params.loopSeconds: 1以上60以下。P0では原則10。",
    "",
    `- タイトル: ${theme.title}`,
    `- キーワード: ${theme.keywords.join(", ")}`,
    `- 想定尺（分）: ${theme.targetMinutes}`,
    `- フォーマット: ${theme.format}`,
    `- 対象: ${theme.audience}`,
    `- トーン: ${theme.tone}`
  ].join("\n");
}
